[tool.poetry]
name = "korean-news-raptor"
version = "0.1.0"
description = ""
authors = ["yunyoseob <imyoseob@naver.com>"]
readme = "README.md"
packages = [{include = "app"}]

[tool.poetry.dependencies]
python = "^3.10"
python-dotenv = "^1.0.1"
openai = "0.28"
gradio = "^4.38.1"
pymilvus = "^2.4.4"
milvus-lite = "^2.4.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
